package cs3500.threetrios.view;

import java.io.IOException;

import cs3500.threetrios.model.ReadonlyThreeTriosModel;
import cs3500.threetrios.model.ThreeTriosModel;

/**
 * A textual view implementation for the Three Trios game.
 */
public class ThreeTriosTextView implements ThreeTriosView {

  private final ReadonlyThreeTriosModel<?> model;
  private final Appendable out;

  /**
   * Uses provided game model to create a text view.
   *
   * @param model the game model
   * @throws IllegalArgumentException if model is null
   */
  public ThreeTriosTextView(ReadonlyThreeTriosModel<?> model) {
    if (model == null) {
      throw new IllegalArgumentException("Cannot be null");
    }
    this.model = model;
    out = new StringBuilder();
  }

  /**
   * Constructs a ThreeTriosTextView with the given model.
   *
   * @param model the game model
   * @param out   the output destination
   * @throws IllegalArgumentException if model or out is null
   */
  public ThreeTriosTextView(ThreeTriosModel<?> model, Appendable out) {
    if (model == null || out == null) {
      throw new IllegalArgumentException("Cannot be null");
    }
    this.model = model;
    this.out = out;
  }

  @Override
  public void renderBoard() throws IOException {
    // game state generated by model
    out.append(model.toString());
  }

  @Override
  public void renderMessage(String message) throws IOException {
    out.append(message);
  }
}
